# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_libipldr_wrappers", use_symbols = TRUE, package_name = "libipldr")

#' @usage NULL
#' @useDynLib libipldr, .registration = TRUE
"_PACKAGE"

# nolint end
